# tomcat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-2
spec:
  selector:
    app: tomcat-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

