# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-2
  template:
    metadata:
      labels:
        app: tomcat-2
    spec:
      containers:
      - name: tomcat-container-2
        image: krishnamsg/complete-prodcution-e2e-pipeline:1.0.0-33
        ports:
        - containerPort: 8080

